apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-argo-application
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: myapp-argo-application
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Joska99/ArgoCD.git
        targetRevision: HEAD
        path: k8s
      destination:
        server: https://kubernetes.default.svc
        namespace: app
