# TODO: apply best practicies

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-pod
  template:
    metadata:
      labels:
        app: simple-pod
    spec:
      containers:
        - name: simple-coontainer
          image: add image
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: stonks-pod-service
spec:
  type: LoadBalancer
  selector:
    app: stonks
  ports:
    - port: 8080 # Default port for image